victoire_core:
    widgets:
        Triptych:
            class: "Victoire\\Widget\\TriptychBundle\\Entity\\WidgetTriptych"
            name: Triptych
            
jms_translation:
    configs:
        victoire_triptych_bundle:
            dirs: ["@VictoireTriptychBundle"]
            output_dir: "@VictoireTriptychBundle/Resources/translations"
