services:
    victoire_core.widget_tryptich_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Tryptich }

    #entity alias
    victoire.widget.tryptich:
        class: Victoire\Widget\TryptichBundle\Entity\WidgetTryptich

    #form alias
    victoire.widget.form.tryptich:
        class: Victoire\Widget\TryptichBundle\Form\WidgetTryptichType
        tags:
            - { name: form.type , alias: victoire_widget_form_tryptich }

    victoire.widget.form.tryptich.col:
        class: Victoire\Widget\TryptichBundle\Form\ColType
        tags:
            - { name: form.type , alias: victoire_widget_form_tryptich_col }
