services:
    victoire_core.widget_triptych_content_resolver:
        class: Victoire\Widget\TriptychBundle\Resolver\WidgetTriptychContentResolver
        parent: victoire_widget.base_widget_content_resolver
        arguments:
            - @victoire_widget.twig.link_extension
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Triptych }

    #entity alias
    victoire.widget.triptych:
        class: Victoire\Widget\TriptychBundle\Entity\WidgetTriptych

    #form alias
    victoire.widget.form.triptych:
        class: Victoire\Widget\TriptychBundle\Form\WidgetTriptychType
        tags:
            - { name: form.type , alias: victoire_widget_form_triptych }

    victoire.widget.form.triptych.col:
        class: Victoire\Widget\TriptychBundle\Form\ColType
        tags:
            - { name: form.type , alias: victoire_widget_form_triptych_col }
